# Generated by Django 5.2.14 on 2026-06-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(max_length=500)),
                (
                    "face_shape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oval", "oval"),
                            ("round", "round"),
                            ("square", "square"),
                            ("oblong", "oblong"),
                            ("heart", "heart"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "face_point",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upper", "upper"),
                            ("middle", "middle"),
                            ("lower", "lower"),
                            ("golden", "golden"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "skin_tone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spring", "spring"),
                            ("summer", "summer"),
                            ("fall", "fall"),
                            ("winter", "winter"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("skin_lab_b", models.FloatField(blank=True, null=True)),
                ("ratio_face_wh", models.FloatField(blank=True, null=True)),
                ("ratio_jaw_cheek", models.FloatField(blank=True, null=True)),
                ("ratio_forehead_cheek", models.FloatField(blank=True, null=True)),
                ("ratio_upper_third", models.FloatField(blank=True, null=True)),
                ("ratio_middle_third", models.FloatField(blank=True, null=True)),
                ("ratio_lower_third", models.FloatField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analysis_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HairStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hair_code", models.CharField(blank=True, max_length=5, null=True)),
                ("style_name", models.CharField(max_length=100)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "hair_styles",
            },
        ),
        migrations.CreateModel(
            name="MakeupStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style_name", models.CharField(max_length=100)),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "makeup_styles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=6
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("admin", "admin")], max_length=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="StyleMappingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hair", "hair"),
                            ("makeup", "makeup"),
                            ("ootd", "ootd"),
                        ],
                        max_length=6,
                    ),
                ),
                ("style_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_mappings",
                        to="app.analysissession",
                    ),
                ),
                (
                    "hair_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="style_mappings",
                        to="app.hairstyle",
                    ),
                ),
                (
                    "makeup_style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="style_mappings",
                        to="app.makeupstyle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_mappings",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "db_table": "style_mapping_list",
            },
        ),
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_image_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_saved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_results",
                        to="app.analysissession",
                    ),
                ),
                (
                    "hair_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hair_results",
                        to="app.stylemappinglist",
                    ),
                ),
                (
                    "makeup_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeup_results",
                        to="app.stylemappinglist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_results",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="analysissession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_sessions",
                to="app.user",
            ),
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("hair", "hair"), ("makeup", "makeup")], max_length=6
                    ),
                ),
                ("feedback_text", models.TextField(blank=True, null=True)),
                (
                    "applied_style_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "simulation_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="app.simulationresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_feedback",
            },
        ),
    ]
