# Generated by Django 5.2.14 on 2026-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfeedback",
            name="feedback_text",
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="img_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="role",
            field=models.CharField(
                choices=[("ai", "ai"), ("user", "user")], default="user", max_length=4
            ),
            preserve_default=False,
        ),
    ]
