# Generated by Django 5.2.14 on 2026-06-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_userfeedback_feedback_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfeedback",
            name="role",
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="ai_chat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="user_chat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="simulation_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedbacks",
                to="app.simulationresult",
            ),
        ),
    ]
