# Generated by Django 5.2.14 on 2026-06-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_makeup_styles_dedup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makeupstyle",
            name="style_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
