# Generated by Django 5.2.14 on 2026-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_makeup_style_code_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationresult",
            name="hair_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="simulationresult",
            name="makeup_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
