name: Django CI & Branch Check
on:
  pull_request:
    branches: ["main"]
jobs:
  check-behind:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: main 최신화 체크
        run: |
          git fetch origin main
          BEHIND_COUNT=$(git rev-list --count HEAD..origin/main)

          if [ "$BEHIND_COUNT" -gt 0 ]; then
            echo "이 branch는 main보다 $BEHIND_COUNT 개의 커밋이 뒤처져 있습니다!"
            echo "로컬에서 'git merge main' 또는 'git rebase main'을 실행해 최신화해주세요."
            exit 1
          else
            echo "최신 main 상태와 일치합니다."
          fi
  django-check:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ci-dummy-secret-key
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: styleflow.settings
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4
      - name: Python 3.10 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: pip 업그레이드
        run: python -m pip install --upgrade pip
      - name: 패키지 설치
        run: pip install -r requirements.txt
      - name: Django 문법 및 설정 체크
        run: python backend/manage.py check
